version: '3'

services:
  django:
    build: .
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env
  code_server:
    image: codercom/code-server:latest
    environment:
      - PASSWORD=changeme
    volumes:
      - ./workspace:/home/coder/project
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - django
      - code_server

volumes:
  static_volume:
